#!/usr/bin/env python
"""Fig.7 -- Individual noise source impact on STIRAP fidelity (Scenario B).

Bar chart showing the infidelity (1 - F) contribution from each noise channel
when applied individually to an otherwise noiseless STIRAP pulse.
Loads real data from results/noise_channel_sweep_B.json (generated by run_experiments.py).
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))

from src.plotting.plot_config import *

# ---------------------------------------------------------------
# Load real data
# ---------------------------------------------------------------
data_path = os.path.join(os.path.dirname(__file__), '../../results/noise_channel_sweep_B.json')

if os.path.exists(data_path):
    with open(data_path) as f:
        sweep_data = json.load(f)

    channel_keys = ['decay', 'doppler', 'position', 'amplitude', 'phase', 'all']
    noise_labels = [
        'Rydberg\ndecay',
        'Doppler',
        'Position\njitter',
        'Laser\namplitude',
        'Phase\nnoise',
        'All\ncombined',
    ]
    infidelities = [sweep_data[k]['infidelity'] for k in channel_keys]
    std_devs = [sweep_data[k].get('std_F', 0.0) for k in channel_keys]
    print(f"Loaded real data from {data_path}")
else:
    print(f"WARNING: {data_path} not found. Run: python run_experiments.py --scenario B")
    sys.exit(1)

bar_colors = [
    COLORS['red'],
    COLORS['blue'],
    COLORS['orange'],
    COLORS['green'],
    COLORS['purple'],
    COLORS['brown'],
]

# ---------------------------------------------------------------
# Plot
# ---------------------------------------------------------------
fig, ax = plt.subplots(figsize=DOUBLE_COL)

x = np.arange(len(noise_labels))
bars = ax.bar(x, infidelities, width=0.55, color=bar_colors, edgecolor='black',
              linewidth=0.5, zorder=3, yerr=std_devs, capsize=3)

# Value labels on top of bars
for bar, val in zip(bars, infidelities):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + max(infidelities) * 0.03,
            f'{val:.4f}', ha='center', va='bottom', fontsize=9)

ax.set_xticks(x)
ax.set_xticklabels(noise_labels, fontsize=10)
ax.set_ylabel(r'Infidelity $1 - F$')
ax.set_title('Scenario B: Individual noise source impact on STIRAP')
ax.set_ylim(0, max(infidelities) * 1.45)
ax.grid(axis='y', alpha=0.3, zorder=0)

outpath = os.path.join(os.path.dirname(__file__), '../../', FIGURE_DIR, 'fig07_noise_impact.pdf')
os.makedirs(os.path.dirname(outpath), exist_ok=True)
fig.savefig(outpath)
fig.savefig(outpath.replace('.pdf', '.png'))
plt.close(fig)
print(f"Saved {os.path.abspath(outpath)}")
