#!/usr/bin/env python
"""Fig.8 -- Traditional algorithm performance ceiling vs gate time.

Shows STIRAP and GRAPE fidelity as a function of T_gate.
Loads real data from results/gate_time_sweep.json (generated by run_experiments.py).
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))

from src.plotting.plot_config import *

# ---------------------------------------------------------------
# Load real data
# ---------------------------------------------------------------
data_path = os.path.join(os.path.dirname(__file__), '../../results/gate_time_sweep.json')

if os.path.exists(data_path):
    with open(data_path) as f:
        sweep_data = json.load(f)

    T_us = np.array(sweep_data['T_gates'])  # already in us
    F_stirap = np.array(sweep_data['stirap'])
    F_grape = np.array(sweep_data['grape'])
    print(f"Loaded real data from {data_path}")
else:
    print(f"WARNING: {data_path} not found. Run: python run_experiments.py --scenario B")
    sys.exit(1)

# ---------------------------------------------------------------
# Scenario markers
# ---------------------------------------------------------------
T_A = 5.0   # us
T_B = 0.3   # us

# ---------------------------------------------------------------
# Plot
# ---------------------------------------------------------------
fig, ax = plt.subplots(figsize=DOUBLE_COL)

ax.semilogx(T_us, F_stirap, 'o-', color=COLORS['blue'], linewidth=1.8,
            markersize=6, label='STIRAP')
ax.semilogx(T_us, F_grape, 's-', color=COLORS['orange'], linewidth=1.8,
            markersize=6, label='GRAPE')

# Fault-tolerant threshold
ax.axhline(0.999, color='gray', linestyle='--', linewidth=1.0,
           label=r'$F = 0.999$ (fault-tolerant)')

# Scenario markers
ax.axvline(T_B, color=COLORS['green'], linestyle=':', linewidth=1.2, alpha=0.7)
ax.text(T_B * 1.15, 0.50, 'Scenario B\n(0.3 $\\mu$s)', fontsize=9,
        color=COLORS['green'], va='center')
ax.axvline(T_A, color=COLORS['red'], linestyle=':', linewidth=1.2, alpha=0.7)
ax.text(T_A * 1.15, 0.50, 'Scenario A\n(5 $\\mu$s)', fontsize=9,
        color=COLORS['red'], va='center')

ax.set_xlabel(r'Gate time $T_{\mathrm{gate}}$ ($\mu$s)')
ax.set_ylabel(r'Fidelity $F$')
ax.set_title('Traditional algorithm performance vs gate time')
ax.legend(loc='lower right', fontsize=10)
ax.set_ylim(0.0, 1.02)
ax.set_xlim(T_us.min() * 0.8, T_us.max() * 1.3)
ax.grid(True, alpha=0.3, which='both')

outpath = os.path.join(os.path.dirname(__file__), '../../', FIGURE_DIR, 'fig08_traditional_ceiling.pdf')
os.makedirs(os.path.dirname(outpath), exist_ok=True)
fig.savefig(outpath)
fig.savefig(outpath.replace('.pdf', '.png'))
plt.close(fig)
print(f"Saved {os.path.abspath(outpath)}")
