#!/usr/bin/env python
"""Fig.13 -- Pulse shape comparison: STIRAP vs PPO.

Top subplot: Rabi frequency Omega(t)/2pi in MHz.
Bottom subplot: Detuning Delta(t)/2pi in MHz.
STIRAP uses sin^2 envelope with Delta=0.  PPO pulse loaded from real rollout.
Loads PPO data from results/ppo_pulse_B.json (generated by run_experiments.py).
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))

from src.plotting.plot_config import *
from src.physics.constants import SCENARIOS

# ---------------------------------------------------------------
# Time axis and STIRAP pulse (Scenario B, analytic)
# ---------------------------------------------------------------
cfg = SCENARIOS['B']
T_gate = cfg['T_gate']
n_atoms = cfg['n_atoms']

Omega_max_stirap = 2 * np.pi / (np.sqrt(n_atoms) * T_gate)
n_pts = 300
t_s_stirap = np.linspace(0, T_gate, n_pts)
t_us_stirap = t_s_stirap * 1e6

Omega_stirap = Omega_max_stirap * np.sin(np.pi * t_s_stirap / T_gate) ** 2
Delta_stirap = np.zeros_like(t_s_stirap)

Omega_stirap_MHz = Omega_stirap / (2 * np.pi * 1e6)
Delta_stirap_MHz = Delta_stirap / (2 * np.pi * 1e6)

# ---------------------------------------------------------------
# Load real PPO pulse
# ---------------------------------------------------------------
data_path = os.path.join(os.path.dirname(__file__), '../../results/ppo_pulse_B.json')

if os.path.exists(data_path):
    with open(data_path) as f:
        pulse_data = json.load(f)

    omegas = np.array(pulse_data['omega'])
    deltas = np.array(pulse_data['delta'])
    T_gate_ppo = pulse_data['T_gate']
    n_steps = len(omegas)
    dt = T_gate_ppo / n_steps
    # Center of each time step
    t_s_ppo = np.array([(i + 0.5) * dt for i in range(n_steps)])
    t_us_ppo = t_s_ppo * 1e6

    Omega_ppo_MHz = omegas / (2 * np.pi * 1e6)
    Delta_ppo_MHz = deltas / (2 * np.pi * 1e6)

    final_F = pulse_data.get('final_fidelity', None)
    if final_F is not None:
        print(f"PPO noiseless fidelity: {final_F:.4f}")
    print(f"Loaded real PPO pulse from {data_path}")
else:
    print(f"WARNING: {data_path} not found. Run: python run_experiments.py --scenario B")
    sys.exit(1)

# ---------------------------------------------------------------
# Plot
# ---------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(DOUBLE_COL[0], DOUBLE_COL[1] * 1.1),
                                sharex=True)

# Top: Omega(t)
ax1.plot(t_us_stirap, Omega_stirap_MHz, '-', color=COLORS['blue'], linewidth=1.8,
         label='STIRAP')
ax1.step(t_us_ppo, Omega_ppo_MHz, '-', color=COLORS['red'], linewidth=1.8,
         where='mid', label='PPO')
ax1.set_ylabel(r'$\Omega(t)/2\pi$ (MHz)')
ax1.legend(loc='upper right', fontsize=10)
ax1.set_title('Pulse shape comparison (Scenario B)')
ax1.grid(True, alpha=0.3)
ax1.set_ylim(bottom=0)

# Bottom: Delta(t)
ax2.plot(t_us_stirap, Delta_stirap_MHz, '-', color=COLORS['blue'], linewidth=1.8,
         label='STIRAP')
ax2.step(t_us_ppo, Delta_ppo_MHz, '-', color=COLORS['red'], linewidth=1.8,
         where='mid', label='PPO')
ax2.set_xlabel(r'Time ($\mu$s)')
ax2.set_ylabel(r'$\Delta(t)/2\pi$ (MHz)')
ax2.legend(loc='upper right', fontsize=10)
ax2.grid(True, alpha=0.3)
ax2.axhline(0, color='gray', linewidth=0.5, linestyle='-')

fig.tight_layout()

outpath = os.path.join(os.path.dirname(__file__), '../../', FIGURE_DIR, 'fig13_pulse_comparison.pdf')
os.makedirs(os.path.dirname(outpath), exist_ok=True)
fig.savefig(outpath)
fig.savefig(outpath.replace('.pdf', '.png'))
plt.close(fig)
print(f"Saved {os.path.abspath(outpath)}")
