#!/usr/bin/env python
"""Fig.11 -- Robustness to amplitude miscalibration.

Real data showing mean fidelity vs relative amplitude error
for STIRAP, GRAPE, and PPO+DR.
Loads from results/robustness_sweep_B.json (generated by run_experiments.py).
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))

from src.plotting.plot_config import *

# ---------------------------------------------------------------
# Load real data
# ---------------------------------------------------------------
data_path = os.path.join(os.path.dirname(__file__), '../../results/robustness_sweep_B.json')

if os.path.exists(data_path):
    with open(data_path) as f:
        sweep_data = json.load(f)

    delta_pct = np.array(sweep_data['delta_pct'])
    F_stirap = np.array(sweep_data['stirap'])
    F_grape = np.array(sweep_data['grape'])
    F_ppo_raw = sweep_data['ppo']
    has_ppo = all(v is not None for v in F_ppo_raw)
    F_ppo = np.array(F_ppo_raw) if has_ppo else None
    print(f"Loaded real data from {data_path}")
else:
    print(f"WARNING: {data_path} not found. Run: python run_experiments.py --scenario B")
    sys.exit(1)

# ---------------------------------------------------------------
# Plot
# ---------------------------------------------------------------
fig, ax = plt.subplots(figsize=DOUBLE_COL)

ax.plot(delta_pct, F_stirap, 'o-', color=COLORS['blue'], linewidth=1.8,
        markersize=6, label='STIRAP')
ax.plot(delta_pct, F_grape, 's-', color=COLORS['orange'], linewidth=1.8,
        markersize=6, label='GRAPE')
if F_ppo is not None:
    ax.plot(delta_pct, F_ppo, '^-', color=COLORS['green'], linewidth=1.8,
            markersize=6, label='PPO+DR')

ax.set_xlabel(r'Amplitude miscalibration $\delta\Omega / \Omega$ (%)')
ax.set_ylabel(r'Mean fidelity $\langle F \rangle$')
ax.set_title('Robustness to amplitude error (Scenario B)')
ax.legend(loc='lower left', fontsize=10)
ax.set_xlim(-0.2, max(delta_pct) + 0.2)
y_min = min(F_stirap.min(), F_grape.min())
if F_ppo is not None:
    y_min = min(y_min, F_ppo.min())
ax.set_ylim(max(0, y_min - 0.05), 1.005)
ax.grid(True, alpha=0.3)

outpath = os.path.join(os.path.dirname(__file__), '../../', FIGURE_DIR, 'fig11_robustness.pdf')
os.makedirs(os.path.dirname(outpath), exist_ok=True)
fig.savefig(outpath)
fig.savefig(outpath.replace('.pdf', '.png'))
plt.close(fig)
print(f"Saved {os.path.abspath(outpath)}")
